name: Go CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./... # The -race flag is great for finding concurrency issues
